### ISSUE TITLE
Cursor shape vim

### ISSUE THREAD

**Issue by d-nnis** [blueyed/dotfiles#4]
Some weird signs are being thrown in my terminal when using the settings for cursor shape (approx. from line 3957). After having started vim with your vimrc those signs appear frequently in my prompt next to the cursor as well. See screenshot. How can I find out what settings do work for me?
This site did not yield any answers about that issue: http://vim.wikia.com/wiki/Configuring_the_cursor
Thanks for sharing (it's caring)!  :jack_o_lantern:

> $TERM=screen-256color

XFCE4 Terminal-Emulator.
zsh 5.0.7 (x86_64-pc-linux-gnu)
Also in GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)

**Update**

- In (U)Xterm it seems to work fine (only colored change).
- Also with the last section activated (_escape codes for tmux_) it does not work properly

![vim-cursorshape](https://cloud.githubusercontent.com/assets/1454499/23341423/bf2d9dee-fc47-11e6-8ed0-0952f53d5fc8.png)

**Comment by blueyed** [comment]
Does it only happen in tmux?
What do you use for `&t_SI` / `&t_EI` in the end?  `:echo [&t_EI, &t_SI]`
Do you set `$_USE_XTERM_CURSOR_CODES=1`?
(see https://github.com/blueyed/oh-my-zsh/blob/5a3e39bd3a73fd3b21bc06f70d8ec74ac6fd2c38/themes/blueyed.zsh-theme#L874-L887)

**Comment by blueyed** [comment]
According to http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes XFCE terminal does not seem to support escape codes for changing it.

The mechanism provided there changes the terminalrc globally - seems very ugly?!

```
if has("autocmd")
  au InsertEnter * silent execute "!sed -i.bak -e 's/TERMINAL_CURSOR_SHAPE_BLOCK/TERMINAL_CURSOR_SHAPE_UNDERLINE/' ~/.config/xfce4/terminal/terminalrc"
  au InsertLeave * silent execute "!sed -i.bak -e 's/TERMINAL_CURSOR_SHAPE_UNDERLINE/TERMINAL_CURSOR_SHAPE_BLOCK/' ~/.config/xfce4/terminal/terminalrc"
  au VimLeave * silent execute "!sed -i.bak -e 's/TERMINAL_CURSOR_SHAPE_UNDERLINE/TERMINAL_CURSOR_SHAPE_BLOCK/' ~/.config/xfce4/terminal/terminalrc"
endif
```

**Comment by blueyed** [comment]
My suggestion is to use Neovim and/or another terminal emulator.

**Comment by blueyed** [comment]
Not sure if Neovim in XFCE terminal will work though.. from `man nvim`:

```
NVIM_TUI_ENABLE_CURSOR_SHAPE

Set to 0 to prevent Nvim from changing the cursor shape.  Set to 1 to
enable non-blinking mode-sensitive cursor (this is the default).  Set to
2 to enable blinking mode-sensitive cursor.  Host terminal must support
the DECSCUSR CSI escape sequence.

Depending on the terminal emulator, using this option with nvim under
tmux(1) might require adding the following to ~/.tmux.conf:

      set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

See terminal-overrides in the tmux(1) manual page for more information.
```

**Comment by d-nnis** [comment]
- In XFCE terminal in works fine while not in Tmux.
- The afore mentioned code from http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes works fine in Tmux in conjunction with the _Wrap escape codes for tmux_ code activated.
- Color and cursor shape work as (apparently) expected!

Cudos to YOU!   :rocket:

![vim-cursorshape_fixed](https://cloud.githubusercontent.com/assets/1454499/23341663/212f1a8c-fc4c-11e6-9ed9-125c1edf2983.png)

*PS:*
> :echo [&t_EI, &t_SI]

['^[]12;#5f8700^G', '^[]12;#0087ff^G']

**Comment by d-nnis** [comment]
Urxvt and Neovim will have to wait before they become guests in my userspace.

**Comment by blueyed** [comment]
You should not need "Wrap escape codes for tmux" when changing the terminalrc?!

xfce4-terminal seems to support the standard xterm sequences though:
```
    let &t_SI = "\<Esc>[5 q"
    let &t_EI = "\<Esc>[1 q"
```

In my setup, `_USE_XTERM_CURSOR_CODES=1` gets set and then the above is used in Vim.

**Comment by blueyed** [comment]
Seems like the Vim wiki page is outdated, maybe since xfce4-terminal switched to libvte or something like that.
